import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is generated from the docs/ folder structure; ordering comes from
// each directory's _category_.json and per-page sidebar_position frontmatter.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
