import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";

/**
 * Schema conventions:
 * - ids: uuid, generated by Postgres
 * - money: bigint minor units (paise), JS number mode — never floats
 *   sign convention: negative = outflow (expense), positive = inflow (income)
 * - timestamps: timestamptz, created_at/updated_at on every table
 * - soft delete / archive: *_at nullable timestamptz
 */

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  displayName: text("display_name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Per-user assumptions used only for forward-looking goal projections. */
export const projectionSettings = pgTable("projection_settings", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Broad-equity annual return assumption (1200 = 12%). */
  equityReturnBps: integer("equity_return_bps").notNull().default(1200),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * `custom` is a generic OpenAI-compatible endpoint (base URL + key + model);
 * the others are named providers with fixed base URLs (see packages/ai/factory).
 */
export const aiProvider = pgEnum("ai_provider", [
  "none",
  "anthropic",
  "ollama",
  "openrouter",
  "deepseek",
  "custom",
]);

/**
 * Per-user AI provider config. Replaces the old global AI_* env vars: the API's
 * AI features and the email extractor both resolve the provider from here. The
 * API key is encrypted at rest with the same secret-box envelope as mailbox
 * secrets (keyed by MAILBOX_SECRET), so the extractor can decrypt it too.
 */
export const aiSettings = pgTable("ai_settings", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  provider: aiProvider("provider").notNull().default("none"),
  /** encrypted API key; "" for ollama/none */
  apiKeyEnc: text("api_key_enc").notNull().default(""),
  /** base URL for ollama/custom; "" otherwise */
  baseUrl: text("base_url").notNull().default(""),
  /** model name; provider default used when "" */
  model: text("model").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * `ppf`, `epf` and `ssy` are accounts rather than holdings because their balance
 * is known exactly — interest is credited at a fixed rate, not estimated. NPS
 * and gold move with a daily NAV/price, so they stay holdings, where a valuation
 * carries the as-of date that makes the estimate honest.
 */
export const accountType = pgEnum("account_type", [
  "bank",
  "cash",
  "credit_card",
  "investment",
  "loan",
  // Generic overdraft/line-of-credit account. It shares drawing-power details
  // with an overdraft home loan but is kept distinct for reporting and labels.
  "overdraft",
  "ppf",
  "epf",
  // Sukanya Samriddhi: a PPF twin (fixed govt rate, credited annually, matures
  // ~21 years out, has an account number). Reuses the scheme-details structure.
  "ssy",
  // Overdraft home loan (SBI Maxgain and its equivalents). A distinct type, not
  // just a loan: you park surplus into it to cut interest and can withdraw it
  // back, so it carries a sanctioned limit and a drawing power a term loan has
  // no notion of. The balance is still what you owe (net of parked surplus), so
  // it lands in the loans bucket like any liability.
  "home_loan_od",
  // DEPRECATED: insurance is now a standalone entity (see insurance_policies),
  // not an account. This enum value is retained only because Postgres cannot drop
  // an enum value; no account uses it and the UI no longer offers it.
  "insurance",
]);

export const accounts = pgTable(
  "accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** human-facing label, e.g. "HDFC Joint" — never parsed; display comes from this alone */
    name: text("name").notNull(),
    type: accountType("type").notNull(),
    /** issuing bank/institution; a lookup key for import matching, not a display badge */
    institution: text("institution"),
    /**
     * Last 4 digits, shown in lists so two HDFC accounts are tellable apart.
     * Derived from bank_details.account_number whenever one exists — see
     * syncAccountLast4 — so the two can never disagree. Set by hand only when
     * the full number isn't recorded.
     */
    accountLast4: text("account_last4"),
    /**
     * Whose account this is. Universal, not bank-only: a card has a name on it
     * and a PPF has a holder. Without this the holder gets packed into `name`
     * ("HDFC Ammu PPF"), which is the same trap the last-4 used to be in.
     */
    holderName: text("holder_name"),
    /**
     * UPI handles that resolve to this account, primary first. Not bank-only —
     * RuPay credit cards link to UPI too, so this can't live on bank_details.
     */
    upiIds: text("upi_ids")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    currency: text("currency").notNull().default("INR"),
    openingBalancePaise: bigint("opening_balance_paise", { mode: "number" })
      .notNull()
      .default(0),
    /**
     * Goal this account is earmarked for; net worth and goal funding group by
     * it. Null = the "Unassigned" bucket. Set-null on goal delete so the account
     * survives. A goal's funded value is the sum of the assets that point here.
     */
    // AnyPgColumn keeps inference stable across the accounts → goals reference
    // (goals is declared after accounts in this file).
    goalId: uuid("goal_id").references((): AnyPgColumn => goals.id, { onDelete: "set null" }),
    sortOrder: integer("sort_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("accounts_user_idx").on(t.userId)],
);

export const categoryKind = pgEnum("category_kind", ["income", "expense"]);

export const categories = pgTable(
  "categories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    kind: categoryKind("kind").notNull(),
    parentId: uuid("parent_id"),
    icon: text("icon").notNull().default(""),
    color: text("color").notNull().default(""),
    sortOrder: integer("sort_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("categories_user_idx").on(t.userId),
    uniqueIndex("categories_user_name_parent_idx").on(t.userId, t.name, t.parentId),
  ],
);

export const transactionSource = pgEnum("transaction_source", ["manual", "import", "recurring"]);

export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    date: date("date").notNull(),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    merchant: text("merchant").notNull().default(""),
    categoryId: uuid("category_id").references(() => categories.id),
    notes: text("notes").notNull().default(""),
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    source: transactionSource("source").notNull().default("manual"),
    /**
     * Insurance policy this expense pays a premium for — a link to an
     * insurance_policies row, kept apart from `accountId` (the account the money
     * left). Null for ordinary transactions. Lets a policy show its premium
     * history without being an account itself. See services/insurance.ts.
     */
    policyId: uuid("policy_id").references((): AnyPgColumn => insurancePolicies.id, {
      onDelete: "set null",
    }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("transactions_user_date_idx").on(t.userId, t.date.desc(), t.id.desc()),
    index("transactions_account_idx").on(t.accountId),
    index("transactions_category_idx").on(t.categoryId),
    index("transactions_policy_idx").on(t.policyId),
  ],
);

export const transactionSplits = pgTable(
  "transaction_splits",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    note: text("note").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("transaction_splits_tx_idx").on(t.transactionId)],
);

export const transferLinks = pgTable(
  "transfer_links",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    outTransactionId: uuid("out_transaction_id")
      .notNull()
      .unique()
      .references(() => transactions.id, { onDelete: "cascade" }),
    inTransactionId: uuid("in_transaction_id")
      .notNull()
      .unique()
      .references(() => transactions.id, { onDelete: "cascade" }),
    auto: boolean("auto").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("transfer_links_user_idx").on(t.userId)],
);

// ---------- Phase 2: imports & rules ----------

export const importStatus = pgEnum("import_status", ["staged", "committed", "rolled_back"]);

export const imports = pgTable(
  "imports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    fileName: text("file_name").notNull(),
    status: importStatus("status").notNull().default("staged"),
    mapping: jsonb("mapping"),
    headers: text("headers").array().notNull().default(sql`'{}'::text[]`),
    rowCount: integer("row_count").notNull().default(0),
    errorCount: integer("error_count").notNull().default(0),
    committedAt: timestamp("committed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("imports_user_idx").on(t.userId)],
);

export const importRows = pgTable(
  "import_rows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importId: uuid("import_id")
      .notNull()
      .references(() => imports.id, { onDelete: "cascade" }),
    rowIndex: integer("row_index").notNull(),
    raw: jsonb("raw").notNull(),
    date: date("date"),
    amountPaise: bigint("amount_paise", { mode: "number" }),
    merchant: text("merchant").notNull().default(""),
    rawMerchant: text("raw_merchant").notNull().default(""),
    notes: text("notes").notNull().default(""),
    categoryId: uuid("category_id"),
    dedupeHash: text("dedupe_hash"),
    duplicate: boolean("duplicate").notNull().default(false),
    include: boolean("include").notNull().default(true),
    error: text("error"),
    transactionId: uuid("transaction_id"),
  },
  (t) => [
    index("import_rows_import_idx").on(t.importId),
    index("import_rows_hash_idx").on(t.dedupeHash),
  ],
);

export const importPresets = pgTable(
  "import_presets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    name: text("name").notNull(),
    mapping: jsonb("mapping").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("import_presets_account_idx").on(t.userId, t.accountId)],
);

export const merchantRules = pgTable(
  "merchant_rules",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    match: text("match").notNull(),
    replacement: text("replacement").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("merchant_rules_user_match_idx").on(t.userId, t.match)],
);

// ---------- Phase 3: budgets, notifications, recurring ----------

export const budgetPeriod = pgEnum("budget_period", ["monthly", "annual"]);

export const budgets = pgTable(
  "budgets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    period: budgetPeriod("period").notNull().default("monthly"),
    /** "2026-07" for monthly, "2026" for annual */
    periodKey: text("period_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("budgets_user_period_idx").on(t.userId, t.period, t.periodKey)],
);

export const budgetLines = pgTable(
  "budget_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    budgetId: uuid("budget_id")
      .notNull()
      .references(() => budgets.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "cascade" }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    rollover: boolean("rollover").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("budget_lines_budget_category_idx").on(t.budgetId, t.categoryId)],
);

/** Dedup ledger: one alert per (period, category, threshold) — never re-fires. */
export const budgetAlerts = pgTable(
  "budget_alerts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    periodKey: text("period_key").notNull(),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "cascade" }),
    threshold: integer("threshold").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("budget_alerts_unique_idx").on(t.userId, t.periodKey, t.categoryId, t.threshold),
  ],
);

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    type: text("type").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull().default(""),
    data: jsonb("data"),
    readAt: timestamp("read_at", { withTimezone: true }),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("notifications_user_idx").on(t.userId, t.createdAt.desc())],
);

export const recurringFrequency = pgEnum("recurring_frequency", [
  "daily",
  "weekly",
  "monthly",
  "yearly",
]);

export const recurringKind = pgEnum("recurring_kind", [
  "none",
  "bill",
  "subscription",
  "insurance",
  "emi",
]);

export const recurringTemplates = pgTable(
  "recurring_templates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    categoryId: uuid("category_id").references(() => categories.id),
    merchant: text("merchant").notNull(),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    notes: text("notes").notNull().default(""),
    frequency: recurringFrequency("frequency").notNull(),
    interval: integer("interval").notNull().default(1),
    nextDueDate: date("next_due_date").notNull(),
    endDate: date("end_date"),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    /** bill/subscription/insurance/EMI typing for the Bills view; none = plain recurring */
    kind: recurringKind("kind").notNull().default("none"),
    /** reminder lead days; null = per-kind default (3, annual 14) */
    remindDays: integer("remind_days"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("recurring_templates_user_idx").on(t.userId, t.nextDueDate)],
);

// ---------- Phase 4: goals, bills, notification prefs ----------

export const goalType = pgEnum("goal_type", [
  "savings",
  "emergency_fund",
  "vacation",
  "home",
  "vehicle",
  "education",
  "retirement",
  "custom",
]);

export const goals = pgTable(
  "goals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    type: goalType("type").notNull().default("savings"),
    targetPaise: bigint("target_paise", { mode: "number" }),
    /** emergency_fund preset: target = N months of trailing average expenses */
    targetMonths: integer("target_months"),
    targetDate: date("target_date"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("goals_user_idx").on(t.userId)],
);

/** Generic once-only ledger for milestone/reminder/threshold notifications. */
export const alertLedger = pgTable(
  "alert_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    kind: text("kind").notNull(),
    refKey: text("ref_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("alert_ledger_unique_idx").on(t.userId, t.kind, t.refKey)],
);

export const subscriptionDismissals = pgTable(
  "subscription_dismissals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    merchant: text("merchant").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("subscription_dismissals_unique_idx").on(t.userId, t.merchant)],
);

export const notificationPrefs = pgTable(
  "notification_prefs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** budget | bill | goal | large_transaction | low_balance */
    type: text("type").notNull(),
    /** null = applies to all accounts */
    accountId: uuid("account_id").references(() => accounts.id, { onDelete: "cascade" }),
    enabled: boolean("enabled").notNull().default(true),
    thresholdPaise: bigint("threshold_paise", { mode: "number" }),
    leadDays: integer("lead_days"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("notification_prefs_user_idx").on(t.userId, t.type)],
);

export const attachments = pgTable(
  "attachments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    storedPath: text("stored_path").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("attachments_tx_idx").on(t.transactionId)],
);

// ---------- Phase 5: cards, EMIs, holdings, net worth ----------

export const cardNetwork = pgEnum("card_network", [
  "visa",
  "mastercard",
  "amex",
  "rupay",
  "diners",
]);

/**
 * Issuer and last-4 live on `accounts` (institution/accountLast4) — every
 * account has them. Only genuinely card-specific fields belong here.
 */
export const cardDetails = pgTable("card_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  network: cardNetwork("network"),
  /** product name, e.g. "Regalia Gold" */
  productName: text("product_name").notNull().default(""),
  /**
   * Registered mobile (10 digits, no country code) for building the card's
   * bill-payment UPI VPA — e.g. Axis `CC.91<mobile><last4>@axisbank`. Empty when
   * unknown or the issuer has no VPA scheme.
   */
  billMobile: text("bill_mobile").notNull().default(""),
  /** statement close day of month (1–28) */
  cycleDay: integer("cycle_day").notNull().default(1),
  /** payment due day of month (1–28); first occurrence after the close */
  dueDay: integer("due_day").notNull().default(15),
  creditLimitPaise: bigint("credit_limit_paise", { mode: "number" }).notNull().default(0),
  /** alert when utilization crosses this percentage; null disables */
  utilizationAlertPct: integer("utilization_alert_pct").default(30),
  remindDays: integer("remind_days").notNull().default(3),
  /** reward points earned per ₹100 spent (0 = no program) */
  earnRatePer100: integer("earn_rate_per_100").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Extra detail for `ppf`/`epf` accounts. Mirrors the card_details pattern: a
 * 1:1 optional extension keyed by account, so the core accounts table stays
 * free of type-specific columns.
 */
export const bankAccountSubtype = pgEnum("bank_account_subtype", [
  "savings",
  "current",
  "salary",
  "nre",
  "nro",
]);

/**
 * The details you'd read out to someone paying you. Holder name and UPI live on
 * `accounts` (every type has them); only bank-specific fields belong here.
 *
 * The account number is stored in the clear on purpose: it is a receiving
 * address, not a secret — it's printed on cheques and handed to employers, and
 * money cannot be pulled with it. Encrypting it would cost searchability and a
 * key to lose, while protecting a value that gets given out by design.
 */
export const bankDetails = pgTable("bank_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** full account number; digits only, length varies by bank (9–18) */
  accountNumber: text("account_number").notNull().default(""),
  /** IFSC, e.g. "HDFC0001234" — 4 letters, a literal 0, then 6 alphanumeric */
  ifsc: text("ifsc").notNull().default(""),
  branch: text("branch").notNull().default(""),
  subtype: bankAccountSubtype("subtype"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const retirementDetails = pgTable("retirement_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** annual interest rate in basis points (710 = 7.10%) */
  annualRateBps: integer("annual_rate_bps").notNull().default(0),
  /** PPF matures 15 years from opening; EPF has no maturity, so null */
  maturityDate: date("maturity_date"),
  /** UAN for EPF, account number for PPF — free-form, may be non-numeric */
  referenceNumber: text("reference_number").notNull().default(""),
  /**
   * EPF only: the accumulated Employee Pension Scheme (EPS) balance. EPFO tracks
   * it separately from the provident-fund corpus, so it's a distinct figure the
   * account balance doesn't include. Null for PPF/SSY (and for EPF until entered).
   */
  epsBalancePaise: bigint("eps_balance_paise", { mode: "number" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Extra detail for generic overdraft and `home_loan_od` accounts.
 *
 * Only the sanctioned limit is stored — the amount owed is the account balance
 * (already net of parked surplus, like the bank's own screen), and drawing
 * power derives as limit − owed. Storing surplus separately would let it drift
 * from the balance; deriving it keeps one source of truth.
 */
export const overdraftDetails = pgTable("overdraft_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** drawing-power ceiling, i.e. the bank's "Limit" figure */
  sanctionedLimitPaise: bigint("sanctioned_limit_paise", { mode: "number" }).notNull().default(0),
  /** annual interest rate in basis points (855 = 8.55%); drives the interest-saved estimate */
  annualRateBps: integer("annual_rate_bps").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insuranceKind = pgEnum("insurance_kind", ["life", "health", "vehicle"]);
export const vehicleKind = pgEnum("vehicle_kind", ["car", "bike", "other"]);
export const premiumFrequency = pgEnum("premium_frequency", [
  "monthly",
  "quarterly",
  "half_yearly",
  "yearly",
  "single",
]);

/**
 * An insurance policy — a standalone record, not an account. It carries its own
 * fields (insurer, policy number, sum assured, bonus, dates) rather than the
 * name/holder/UPI/balance an account has, because a policy isn't money you hold.
 * Premiums are tracked as ordinary expense transactions tagged with policy_id
 * (see transactions.policyId); the money flow lives there, only the standing
 * policy terms live here.
 */
export const insurancePolicies = pgTable(
  "insurance_policies",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** short display label for lists, e.g. "LIC Jeevan Anand" */
    name: text("name").notNull(),
    kind: insuranceKind("kind").notNull().default("life"),
    /** car/bike/other for a vehicle policy; null for life/health */
    vehicleType: vehicleKind("vehicle_type"),
    /** insurance company, e.g. "LIC", "Star Health" */
    insurer: text("insurer").notNull().default(""),
    policyNumber: text("policy_number").notNull().default(""),
    /** sum assured (life) / sum insured (health) / IDV (vehicle), in paise */
    sumAssuredPaise: bigint("sum_assured_paise", { mode: "number" }).notNull().default(0),
    /** accrued bonus / loyalty additions (endowment life), in paise */
    bonusPaise: bigint("bonus_paise", { mode: "number" }).notNull().default(0),
    /** premium per payment, in paise */
    premiumPaise: bigint("premium_paise", { mode: "number" }).notNull().default(0),
    premiumFrequency: premiumFrequency("premium_frequency").notNull().default("yearly"),
    /** policy commencement ("started from") */
    startDate: date("start_date"),
    /** next renewal / premium due date */
    renewalDate: date("renewal_date"),
    /** endowment/money-back maturity; null for pure term, health, vehicle */
    maturityDate: date("maturity_date"),
    nominee: text("nominee").notNull().default(""),
    notes: text("notes").notNull().default(""),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("insurance_policies_user_idx").on(t.userId)],
);

export const rewardEntries = pgTable(
  "reward_entries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    /** positive = earned, negative = redeemed/expired */
    points: integer("points").notNull(),
    note: text("note").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("reward_entries_account_idx").on(t.accountId, t.date)],
);

export const emiDetails = pgTable("emi_details", {
  templateId: uuid("template_id")
    .primaryKey()
    .references(() => recurringTemplates.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  principalPaise: bigint("principal_paise", { mode: "number" }).notNull(),
  /** annual interest rate in basis points (875 = 8.75%) */
  annualRateBps: integer("annual_rate_bps").notNull(),
  totalInstallments: integer("total_installments").notNull(),
  /** first installment date */
  startDate: date("start_date").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * No ppf/epf here — those are account types. Their balance is a credited fact,
 * not a valuation, so modelling them as holdings would dress a known number up
 * as an estimate (and give the user two places to record the same thing).
 */
export const assetClass = pgEnum("asset_class", [
  "stock",
  "mutual_fund",
  "etf",
  "gold",
  "fd",
  "nps",
  "other",
]);

/**
 * How a holding's capital gains are taxed. A per-holding fact that can't be
 * inferred from asset_class (a mutual_fund may be equity, debt, or a §50AA
 * specified fund), so it's stored and user-settable. See services/tax-lots.ts.
 */
export const gainsTaxClass = pgEnum("gains_tax_class", [
  "equity",
  "unlisted_shares",
  "other",
  "specified_fund",
  "market_linked_debenture",
  "unlisted_bond",
]);

export const holdings = pgTable(
  "holdings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    assetClass: assetClass("asset_class").notNull(),
    notes: text("notes").notNull().default(""),
    /** optional allocation target, % of portfolio */
    targetPct: integer("target_pct"),
    /**
     * AMFI scheme code (6 digits, e.g. 122639). The key NAV refresh looks up.
     * Null = unmapped: a fund with no AMFI scheme (e.g. a platform product like
     * Kuvera SaveSmart), valued from imported data only and skipped by refresh.
     */
    amfiSchemeCode: integer("amfi_scheme_code"),
    /** MF folio number; free-form, may be non-numeric */
    folioNumber: text("folio_number"),
    /**
     * NAV per unit on 31-Jan-2018 in paise, for grandfathering equity units held
     * before 01-Feb-2018 in the capital-gains statement. Null = not set (no old
     * units, or the user hasn't supplied the FMV). See services/tax-lots.ts.
     */
    grandfatherNavPaise: bigint("grandfather_nav_paise", { mode: "number" }),
    /** Capital-gains tax treatment; guessed from asset class at create, user-editable. */
    gainsTaxClass: gainsTaxClass("gains_tax_class").notNull().default("equity"),
    /** Goal this holding (folio) is earmarked for; null = "Unassigned". See accounts.goalId. */
    goalId: uuid("goal_id").references(() => goals.id, { onDelete: "set null" }),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("holdings_user_idx").on(t.userId)],
);

export const npsTier = pgEnum("nps_tier", ["tier_i", "tier_ii"]);

/** Extra detail for `nps` holdings. */
export const npsDetails = pgTable("nps_details", {
  holdingId: uuid("holding_id")
    .primaryKey()
    .references(() => holdings.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  pran: text("pran").notNull().default(""),
  tier: npsTier("tier").notNull().default("tier_i"),
  /** scheme allocation, percent; E + C + G must total 100 (enforced in the service) */
  equityPct: integer("equity_pct").notNull().default(0),
  corporatePct: integer("corporate_pct").notNull().default(0),
  govtPct: integer("govt_pct").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const goldForm = pgEnum("gold_form", ["physical", "digital", "etf", "sgb"]);

/** Extra detail for `gold` holdings. */
export const goldDetails = pgTable("gold_details", {
  holdingId: uuid("holding_id")
    .primaryKey()
    .references(() => holdings.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  form: goldForm("form").notNull().default("physical"),
  /** karat, physical/digital only (22 or 24); null for etf/sgb */
  purityKarat: integer("purity_karat"),
  /** SGB matures 8 years from issue; null for every other form */
  maturityDate: date("maturity_date"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const holdingValuations = pgTable(
  "holding_valuations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    holdingId: uuid("holding_id")
      .notNull()
      .references(() => holdings.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    valuePaise: bigint("value_paise", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("holding_valuations_unique_idx").on(t.holdingId, t.date)],
);

export const holdingEventType = pgEnum("holding_event_type", ["buy", "sell", "dividend"]);

/** Where an event came from: a statement import, or hand-entered. Drives per-date
 * FIFO-order reconciliation on re-import (imports may re-sequence imported events;
 * manual ones are only ever moved by the user). See services/mf-import.ts. */
export const holdingEventSource = pgEnum("holding_event_source", ["import", "manual"]);

export const holdingEvents = pgTable(
  "holding_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    holdingId: uuid("holding_id")
      .notNull()
      .references(() => holdings.id, { onDelete: "cascade" }),
    type: holdingEventType("type").notNull(),
    date: date("date").notNull(),
    /** always positive; the type carries direction */
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    units: doublePrecision("units"),
    note: text("note").notNull().default(""),
    /**
     * Intra-day order key: the 0-based position of this event *within its
     * (holding, date)*. Both imported and manual events carry one, so a same-day
     * manual sale can sit before an imported buy. `date` is FIFO's primary key,
     * so seq only has to separate events sharing a day (see services/tax-lots.ts).
     * User-editable via the reorder endpoint.
     */
    seq: integer("seq"),
    /** import vs manual; default import (the dominant source). Manual adds set it. */
    source: holdingEventSource("source").notNull().default("import"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("holding_events_holding_idx").on(t.holdingId, t.date)],
);

export const netWorthSnapshots = pgTable(
  "net_worth_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    date: date("date").notNull(),
    assetsPaise: bigint("assets_paise", { mode: "number" }).notNull(),
    liabilitiesPaise: bigint("liabilities_paise", { mode: "number" }).notNull(),
    /** { cash, holdings, investmentAccounts, creditCards, loans } */
    breakdown: jsonb("breakdown"),
    /** true when estimated from ledger history rather than observed */
    estimated: boolean("estimated").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("net_worth_snapshots_unique_idx").on(t.userId, t.date)],
);

// ---------- Phase 7: email → transaction ingestion pipeline ----------
//
// Two containers feed this: the `ingestor` (IMAP → raw email row + queue job)
// and the `extractor` (queue → AI classify/extract → review inbox). See
// packages/shared/src/schemas/email.ts for the wire contract shared between them.

export const mailboxProvider = pgEnum("mailbox_provider", ["google", "microsoft"]);
export const mailboxStatus = pgEnum("mailbox_status", ["active", "disconnected", "error"]);

/**
 * A connected mailbox. Holds the OAuth2 refresh token (encrypted at rest — no
 * password is ever stored) and the IMAP resume watermark so restarts never
 * reprocess mail. One row per mailbox the ingestor polls.
 */
export const mailboxAccounts = pgTable(
  "mailbox_accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    provider: mailboxProvider("provider").notNull(),
    emailAddress: text("email_address").notNull(),
    /** OAuth2 refresh token, encrypted with the app secret; minted into access tokens for XOAUTH2 */
    refreshTokenEnc: text("refresh_token_enc").notNull(),
    folder: text("folder").notNull().default("INBOX"),
    status: mailboxStatus("status").notNull().default("active"),
    lastError: text("last_error"),
    /** IMAP resume watermark: reprocess nothing at or below lastUid for this uidValidity */
    uidValidity: bigint("uid_validity", { mode: "number" }),
    lastUid: bigint("last_uid", { mode: "number" }),
    lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("mailbox_accounts_addr_idx").on(t.userId, t.emailAddress)],
);

/**
 * Per-user OAuth client credentials for a mailbox provider. Each user brings
 * their own Google Cloud OAuth client (there is no shared/global client), so
 * the client id + encrypted secret are stored here and resolved per mailbox by
 * the ingestor. One row per (user, provider).
 */
export const mailboxCredentials = pgTable(
  "mailbox_credentials",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    provider: mailboxProvider("provider").notNull(),
    clientId: text("client_id").notNull(),
    /** OAuth client secret, encrypted with the app secret (same envelope as the refresh token) */
    clientSecretEnc: text("client_secret_enc").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("mailbox_credentials_user_provider_idx").on(t.userId, t.provider)],
);

export const emailClass = pgEnum("email_class", [
  "transaction_alert",
  "card_statement",
  "bill",
  "otp",
  "promo",
  "other",
]);

export const emailIngestStatus = pgEnum("email_ingest_status", [
  "pending",
  "processing",
  "extracted",
  "deferred",
  "ignored",
  "failed",
]);

/**
 * One ingested email. The raw RFC822 message is retained (`raw`) so extraction
 * is replayable after a parser/prompt fix. `messageId` dedupes re-fetches.
 */
export const emailIngestions = pgTable(
  "email_ingestions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    mailboxId: uuid("mailbox_id").references(() => mailboxAccounts.id, { onDelete: "set null" }),
    /** RFC822 Message-ID header; the dedupe key for re-fetched mail */
    messageId: text("message_id").notNull(),
    fromAddr: text("from_addr").notNull().default(""),
    subject: text("subject").notNull().default(""),
    receivedAt: timestamp("received_at", { withTimezone: true }),
    /** full RFC822 message (MIME is ascii-safe), retained for replay */
    raw: text("raw").notNull(),
    classification: emailClass("classification"),
    status: emailIngestStatus("status").notNull().default("pending"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("email_ingestions_msgid_idx").on(t.userId, t.messageId),
    index("email_ingestions_status_idx").on(t.userId, t.status),
  ],
);

export const extractedTxnStatus = pgEnum("extracted_txn_status", [
  "pending",
  "accepted",
  "rejected",
]);
export const txnDirection = pgEnum("txn_direction", ["debit", "credit"]);

/**
 * A transaction the model pulled out of an email — a draft in the review inbox.
 * `amountPaise` is a positive magnitude; `direction` gives the sign applied when
 * the reviewer accepts it into the ledger. Category is never set here (accept is
 * a manual step). `dedupeHash` collapses the alert and the later statement line.
 */
export const extractedTransactions = pgTable(
  "extracted_transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    ingestionId: uuid("ingestion_id")
      .notNull()
      .references(() => emailIngestions.id, { onDelete: "cascade" }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    direction: txnDirection("direction").notNull(),
    occurredAt: date("occurred_at"),
    counterparty: text("counterparty").notNull().default(""),
    suggestedAccountId: uuid("suggested_account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    bankRef: text("bank_ref"),
    sourceQuote: text("source_quote").notNull().default(""),
    confidence: doublePrecision("confidence"),
    /** bank_ref, or a hash of amount+date+counterparty; unique to collapse duplicates */
    dedupeHash: text("dedupe_hash"),
    status: extractedTxnStatus("status").notNull().default("pending"),
    /** set once accepted into the ledger */
    transactionId: uuid("transaction_id").references(() => transactions.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("extracted_transactions_status_idx").on(t.userId, t.status),
    index("extracted_transactions_ingestion_idx").on(t.ingestionId),
    uniqueIndex("extracted_transactions_dedupe_idx").on(t.userId, t.dedupeHash),
  ],
);
