import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Schema conventions:
 * - ids: uuid, generated by Postgres
 * - money: bigint minor units (paise), JS number mode — never floats
 *   sign convention: negative = outflow (expense), positive = inflow (income)
 * - timestamps: timestamptz, created_at/updated_at on every table
 * - soft delete / archive: *_at nullable timestamptz
 */

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  displayName: text("display_name").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * `ppf`, `epf` and `ssy` are accounts rather than holdings because their balance
 * is known exactly — interest is credited at a fixed rate, not estimated. NPS
 * and gold move with a daily NAV/price, so they stay holdings, where a valuation
 * carries the as-of date that makes the estimate honest.
 */
export const accountType = pgEnum("account_type", [
  "bank",
  "cash",
  "credit_card",
  "investment",
  "loan",
  "ppf",
  "epf",
  // Sukanya Samriddhi: a PPF twin (fixed govt rate, credited annually, matures
  // ~21 years out, has an account number). Reuses the scheme-details structure.
  "ssy",
  // Overdraft home loan (SBI Maxgain and its equivalents). A distinct type, not
  // just a loan: you park surplus into it to cut interest and can withdraw it
  // back, so it carries a sanctioned limit and a drawing power a term loan has
  // no notion of. The balance is still what you owe (net of parked surplus), so
  // it lands in the loans bucket like any liability.
  "home_loan_od",
]);

export const accounts = pgTable(
  "accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** human-facing label, e.g. "HDFC Joint" — never parsed; display comes from this alone */
    name: text("name").notNull(),
    type: accountType("type").notNull(),
    /** issuing bank/institution; a lookup key for import matching, not a display badge */
    institution: text("institution"),
    /**
     * Last 4 digits, shown in lists so two HDFC accounts are tellable apart.
     * Derived from bank_details.account_number whenever one exists — see
     * syncAccountLast4 — so the two can never disagree. Set by hand only when
     * the full number isn't recorded.
     */
    accountLast4: text("account_last4"),
    /**
     * Whose account this is. Universal, not bank-only: a card has a name on it
     * and a PPF has a holder. Without this the holder gets packed into `name`
     * ("HDFC Ammu PPF"), which is the same trap the last-4 used to be in.
     */
    holderName: text("holder_name"),
    /**
     * UPI handles that resolve to this account, primary first. Not bank-only —
     * RuPay credit cards link to UPI too, so this can't live on bank_details.
     */
    upiIds: text("upi_ids")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    currency: text("currency").notNull().default("INR"),
    openingBalancePaise: bigint("opening_balance_paise", { mode: "number" })
      .notNull()
      .default(0),
    sortOrder: integer("sort_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("accounts_user_idx").on(t.userId)],
);

export const categoryKind = pgEnum("category_kind", ["income", "expense"]);

export const categories = pgTable(
  "categories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    kind: categoryKind("kind").notNull(),
    parentId: uuid("parent_id"),
    icon: text("icon").notNull().default(""),
    color: text("color").notNull().default(""),
    sortOrder: integer("sort_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("categories_user_idx").on(t.userId),
    uniqueIndex("categories_user_name_parent_idx").on(t.userId, t.name, t.parentId),
  ],
);

export const transactionSource = pgEnum("transaction_source", ["manual", "import", "recurring"]);

export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    date: date("date").notNull(),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    merchant: text("merchant").notNull().default(""),
    categoryId: uuid("category_id").references(() => categories.id),
    notes: text("notes").notNull().default(""),
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    source: transactionSource("source").notNull().default("manual"),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("transactions_user_date_idx").on(t.userId, t.date.desc(), t.id.desc()),
    index("transactions_account_idx").on(t.accountId),
    index("transactions_category_idx").on(t.categoryId),
  ],
);

export const transactionSplits = pgTable(
  "transaction_splits",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    note: text("note").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("transaction_splits_tx_idx").on(t.transactionId)],
);

export const transferLinks = pgTable(
  "transfer_links",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    outTransactionId: uuid("out_transaction_id")
      .notNull()
      .unique()
      .references(() => transactions.id, { onDelete: "cascade" }),
    inTransactionId: uuid("in_transaction_id")
      .notNull()
      .unique()
      .references(() => transactions.id, { onDelete: "cascade" }),
    auto: boolean("auto").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("transfer_links_user_idx").on(t.userId)],
);

// ---------- Phase 2: imports & rules ----------

export const importStatus = pgEnum("import_status", ["staged", "committed", "rolled_back"]);

export const imports = pgTable(
  "imports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    fileName: text("file_name").notNull(),
    status: importStatus("status").notNull().default("staged"),
    mapping: jsonb("mapping"),
    headers: text("headers").array().notNull().default(sql`'{}'::text[]`),
    rowCount: integer("row_count").notNull().default(0),
    errorCount: integer("error_count").notNull().default(0),
    committedAt: timestamp("committed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("imports_user_idx").on(t.userId)],
);

export const importRows = pgTable(
  "import_rows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importId: uuid("import_id")
      .notNull()
      .references(() => imports.id, { onDelete: "cascade" }),
    rowIndex: integer("row_index").notNull(),
    raw: jsonb("raw").notNull(),
    date: date("date"),
    amountPaise: bigint("amount_paise", { mode: "number" }),
    merchant: text("merchant").notNull().default(""),
    rawMerchant: text("raw_merchant").notNull().default(""),
    notes: text("notes").notNull().default(""),
    categoryId: uuid("category_id"),
    dedupeHash: text("dedupe_hash"),
    duplicate: boolean("duplicate").notNull().default(false),
    include: boolean("include").notNull().default(true),
    error: text("error"),
    transactionId: uuid("transaction_id"),
  },
  (t) => [
    index("import_rows_import_idx").on(t.importId),
    index("import_rows_hash_idx").on(t.dedupeHash),
  ],
);

export const importPresets = pgTable(
  "import_presets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    name: text("name").notNull(),
    mapping: jsonb("mapping").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("import_presets_account_idx").on(t.userId, t.accountId)],
);

export const merchantRules = pgTable(
  "merchant_rules",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    match: text("match").notNull(),
    replacement: text("replacement").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("merchant_rules_user_match_idx").on(t.userId, t.match)],
);

// ---------- Phase 3: budgets, notifications, recurring ----------

export const budgetPeriod = pgEnum("budget_period", ["monthly", "annual"]);

export const budgets = pgTable(
  "budgets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    period: budgetPeriod("period").notNull().default("monthly"),
    /** "2026-07" for monthly, "2026" for annual */
    periodKey: text("period_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("budgets_user_period_idx").on(t.userId, t.period, t.periodKey)],
);

export const budgetLines = pgTable(
  "budget_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    budgetId: uuid("budget_id")
      .notNull()
      .references(() => budgets.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "cascade" }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    rollover: boolean("rollover").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("budget_lines_budget_category_idx").on(t.budgetId, t.categoryId)],
);

/** Dedup ledger: one alert per (period, category, threshold) — never re-fires. */
export const budgetAlerts = pgTable(
  "budget_alerts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    periodKey: text("period_key").notNull(),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "cascade" }),
    threshold: integer("threshold").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("budget_alerts_unique_idx").on(t.userId, t.periodKey, t.categoryId, t.threshold),
  ],
);

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    type: text("type").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull().default(""),
    data: jsonb("data"),
    readAt: timestamp("read_at", { withTimezone: true }),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("notifications_user_idx").on(t.userId, t.createdAt.desc())],
);

export const recurringFrequency = pgEnum("recurring_frequency", [
  "daily",
  "weekly",
  "monthly",
  "yearly",
]);

export const recurringKind = pgEnum("recurring_kind", [
  "none",
  "bill",
  "subscription",
  "insurance",
  "emi",
]);

export const recurringTemplates = pgTable(
  "recurring_templates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    categoryId: uuid("category_id").references(() => categories.id),
    merchant: text("merchant").notNull(),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    notes: text("notes").notNull().default(""),
    frequency: recurringFrequency("frequency").notNull(),
    interval: integer("interval").notNull().default(1),
    nextDueDate: date("next_due_date").notNull(),
    endDate: date("end_date"),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    /** bill/subscription/insurance/EMI typing for the Bills view; none = plain recurring */
    kind: recurringKind("kind").notNull().default("none"),
    /** reminder lead days; null = per-kind default (3, annual 14) */
    remindDays: integer("remind_days"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("recurring_templates_user_idx").on(t.userId, t.nextDueDate)],
);

// ---------- Phase 4: goals, bills, notification prefs ----------

export const goalType = pgEnum("goal_type", [
  "savings",
  "emergency_fund",
  "vacation",
  "home",
  "vehicle",
  "education",
  "retirement",
  "custom",
]);

export const goals = pgTable(
  "goals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    type: goalType("type").notNull().default("savings"),
    targetPaise: bigint("target_paise", { mode: "number" }),
    /** emergency_fund preset: target = N months of trailing average expenses */
    targetMonths: integer("target_months"),
    targetDate: date("target_date"),
    /** inflows to a linked account are auto-recorded as contributions */
    accountId: uuid("account_id").references(() => accounts.id),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("goals_user_idx").on(t.userId)],
);

export const goalContributions = pgTable(
  "goal_contributions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    goalId: uuid("goal_id")
      .notNull()
      .references(() => goals.id, { onDelete: "cascade" }),
    transactionId: uuid("transaction_id").references(() => transactions.id, {
      onDelete: "set null",
    }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    date: date("date").notNull(),
    note: text("note").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("goal_contributions_goal_idx").on(t.goalId),
    uniqueIndex("goal_contributions_tx_idx")
      .on(t.goalId, t.transactionId)
      .where(sql`transaction_id is not null`),
  ],
);

/** Generic once-only ledger for milestone/reminder/threshold notifications. */
export const alertLedger = pgTable(
  "alert_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    kind: text("kind").notNull(),
    refKey: text("ref_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("alert_ledger_unique_idx").on(t.userId, t.kind, t.refKey)],
);

export const subscriptionDismissals = pgTable(
  "subscription_dismissals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    merchant: text("merchant").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("subscription_dismissals_unique_idx").on(t.userId, t.merchant)],
);

export const notificationPrefs = pgTable(
  "notification_prefs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** budget | bill | goal | large_transaction | low_balance */
    type: text("type").notNull(),
    /** null = applies to all accounts */
    accountId: uuid("account_id").references(() => accounts.id, { onDelete: "cascade" }),
    enabled: boolean("enabled").notNull().default(true),
    thresholdPaise: bigint("threshold_paise", { mode: "number" }),
    leadDays: integer("lead_days"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("notification_prefs_user_idx").on(t.userId, t.type)],
);

export const attachments = pgTable(
  "attachments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    storedPath: text("stored_path").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("attachments_tx_idx").on(t.transactionId)],
);

// ---------- Phase 5: cards, EMIs, holdings, net worth ----------

export const cardNetwork = pgEnum("card_network", [
  "visa",
  "mastercard",
  "amex",
  "rupay",
  "diners",
]);

/**
 * Issuer and last-4 live on `accounts` (institution/accountLast4) — every
 * account has them. Only genuinely card-specific fields belong here.
 */
export const cardDetails = pgTable("card_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  network: cardNetwork("network"),
  /** product name, e.g. "Regalia Gold" */
  productName: text("product_name").notNull().default(""),
  /** statement close day of month (1–28) */
  cycleDay: integer("cycle_day").notNull().default(1),
  /** payment due day of month (1–28); first occurrence after the close */
  dueDay: integer("due_day").notNull().default(15),
  creditLimitPaise: bigint("credit_limit_paise", { mode: "number" }).notNull().default(0),
  /** alert when utilization crosses this percentage; null disables */
  utilizationAlertPct: integer("utilization_alert_pct").default(30),
  remindDays: integer("remind_days").notNull().default(3),
  /** reward points earned per ₹100 spent (0 = no program) */
  earnRatePer100: integer("earn_rate_per_100").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Extra detail for `ppf`/`epf` accounts. Mirrors the card_details pattern: a
 * 1:1 optional extension keyed by account, so the core accounts table stays
 * free of type-specific columns.
 */
export const bankAccountSubtype = pgEnum("bank_account_subtype", [
  "savings",
  "current",
  "salary",
  "nre",
  "nro",
]);

/**
 * The details you'd read out to someone paying you. Holder name and UPI live on
 * `accounts` (every type has them); only bank-specific fields belong here.
 *
 * The account number is stored in the clear on purpose: it is a receiving
 * address, not a secret — it's printed on cheques and handed to employers, and
 * money cannot be pulled with it. Encrypting it would cost searchability and a
 * key to lose, while protecting a value that gets given out by design.
 */
export const bankDetails = pgTable("bank_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** full account number; digits only, length varies by bank (9–18) */
  accountNumber: text("account_number").notNull().default(""),
  /** IFSC, e.g. "HDFC0001234" — 4 letters, a literal 0, then 6 alphanumeric */
  ifsc: text("ifsc").notNull().default(""),
  branch: text("branch").notNull().default(""),
  subtype: bankAccountSubtype("subtype"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const retirementDetails = pgTable("retirement_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** annual interest rate in basis points (710 = 7.10%) */
  annualRateBps: integer("annual_rate_bps").notNull().default(0),
  /** PPF matures 15 years from opening; EPF has no maturity, so null */
  maturityDate: date("maturity_date"),
  /** UAN for EPF, account number for PPF — free-form, may be non-numeric */
  referenceNumber: text("reference_number").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Extra detail for `home_loan_od` (overdraft home loan) accounts.
 *
 * Only the sanctioned limit is stored — the amount owed is the account balance
 * (already net of parked surplus, like the bank's own screen), and drawing
 * power derives as limit − owed. Storing surplus separately would let it drift
 * from the balance; deriving it keeps one source of truth.
 */
export const overdraftDetails = pgTable("overdraft_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** drawing-power ceiling, i.e. the bank's "Limit" figure */
  sanctionedLimitPaise: bigint("sanctioned_limit_paise", { mode: "number" }).notNull().default(0),
  /** annual interest rate in basis points (855 = 8.55%); drives the interest-saved estimate */
  annualRateBps: integer("annual_rate_bps").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const rewardEntries = pgTable(
  "reward_entries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    /** positive = earned, negative = redeemed/expired */
    points: integer("points").notNull(),
    note: text("note").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("reward_entries_account_idx").on(t.accountId, t.date)],
);

export const emiDetails = pgTable("emi_details", {
  templateId: uuid("template_id")
    .primaryKey()
    .references(() => recurringTemplates.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  principalPaise: bigint("principal_paise", { mode: "number" }).notNull(),
  /** annual interest rate in basis points (875 = 8.75%) */
  annualRateBps: integer("annual_rate_bps").notNull(),
  totalInstallments: integer("total_installments").notNull(),
  /** first installment date */
  startDate: date("start_date").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * No ppf/epf here — those are account types. Their balance is a credited fact,
 * not a valuation, so modelling them as holdings would dress a known number up
 * as an estimate (and give the user two places to record the same thing).
 */
export const assetClass = pgEnum("asset_class", [
  "stock",
  "mutual_fund",
  "etf",
  "gold",
  "fd",
  "nps",
  "other",
]);

export const holdings = pgTable(
  "holdings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    assetClass: assetClass("asset_class").notNull(),
    notes: text("notes").notNull().default(""),
    /** optional allocation target, % of portfolio */
    targetPct: integer("target_pct"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("holdings_user_idx").on(t.userId)],
);

export const npsTier = pgEnum("nps_tier", ["tier_i", "tier_ii"]);

/** Extra detail for `nps` holdings. */
export const npsDetails = pgTable("nps_details", {
  holdingId: uuid("holding_id")
    .primaryKey()
    .references(() => holdings.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  pran: text("pran").notNull().default(""),
  tier: npsTier("tier").notNull().default("tier_i"),
  /** scheme allocation, percent; E + C + G must total 100 (enforced in the service) */
  equityPct: integer("equity_pct").notNull().default(0),
  corporatePct: integer("corporate_pct").notNull().default(0),
  govtPct: integer("govt_pct").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const goldForm = pgEnum("gold_form", ["physical", "digital", "etf", "sgb"]);

/** Extra detail for `gold` holdings. */
export const goldDetails = pgTable("gold_details", {
  holdingId: uuid("holding_id")
    .primaryKey()
    .references(() => holdings.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  form: goldForm("form").notNull().default("physical"),
  /** karat, physical/digital only (22 or 24); null for etf/sgb */
  purityKarat: integer("purity_karat"),
  /** SGB matures 8 years from issue; null for every other form */
  maturityDate: date("maturity_date"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const holdingValuations = pgTable(
  "holding_valuations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    holdingId: uuid("holding_id")
      .notNull()
      .references(() => holdings.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    valuePaise: bigint("value_paise", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("holding_valuations_unique_idx").on(t.holdingId, t.date)],
);

export const holdingEventType = pgEnum("holding_event_type", ["buy", "sell", "dividend"]);

export const holdingEvents = pgTable(
  "holding_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    holdingId: uuid("holding_id")
      .notNull()
      .references(() => holdings.id, { onDelete: "cascade" }),
    type: holdingEventType("type").notNull(),
    date: date("date").notNull(),
    /** always positive; the type carries direction */
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    units: doublePrecision("units"),
    note: text("note").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("holding_events_holding_idx").on(t.holdingId, t.date)],
);

export const netWorthSnapshots = pgTable(
  "net_worth_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    date: date("date").notNull(),
    assetsPaise: bigint("assets_paise", { mode: "number" }).notNull(),
    liabilitiesPaise: bigint("liabilities_paise", { mode: "number" }).notNull(),
    /** { cash, holdings, investmentAccounts, creditCards, loans } */
    breakdown: jsonb("breakdown"),
    /** true when estimated from ledger history rather than observed */
    estimated: boolean("estimated").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("net_worth_snapshots_unique_idx").on(t.userId, t.date)],
);
