import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";

/**
 * Schema conventions:
 * - ids: uuid, generated by Postgres
 * - money: bigint minor units (paise), JS number mode — never floats
 *   sign convention: negative = outflow (expense), positive = inflow (income)
 * - timestamps: timestamptz, created_at/updated_at on every table
 * - soft delete / archive: *_at nullable timestamptz
 */

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  displayName: text("display_name").notNull(),
  /** the seeded, read-only demo account; excluded from the owner-bootstrap count */
  isDemo: boolean("is_demo").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Per-user assumptions used only for forward-looking goal projections. */
export const projectionSettings = pgTable("projection_settings", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  /** Broad-equity annual return assumption (1200 = 12%). */
  equityReturnBps: integer("equity_return_bps").notNull().default(1200),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Per-user profile information. */
export const userProfiles = pgTable("user_profiles", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  dateOfBirth: date("date_of_birth"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const familyRelationship = pgEnum("family_relationship", [
  "spouse",
  "child",
  "parent",
  "sibling",
  "other",
]);

export const educationStage = pgEnum("education_stage", [
  "preschool",
  "primary",
  "secondary",
  "senior_secondary",
  "undergraduate",
  "postgraduate",
  "doctorate",
  "other",
]);

export const familyMembers = pgTable(
  "family_members",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    relationship: familyRelationship("relationship").notNull(),
    dateOfBirth: date("date_of_birth"),
    educationStage: educationStage("education_stage"),
    institution: text("institution"),
    courseOrStream: text("course_or_stream"),
    expectedCompletionYear: integer("expected_completion_year"),
    notes: text("notes"),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("family_members_user_idx").on(t.userId)],
);

/**
 * `custom` is a generic OpenAI-compatible endpoint (base URL + key + model);
 * the others are named providers with fixed base URLs (see packages/ai/factory).
 */
export const aiProvider = pgEnum("ai_provider", [
  "none",
  "anthropic",
  "ollama",
  "openrouter",
  "deepseek",
  "custom",
]);

/**
 * Per-user AI provider config. Replaces the old global AI_* env vars: the API's
 * AI features and the email extractor both resolve the provider from here. The
 * API key is encrypted at rest with the same secret-box envelope as mailbox
 * secrets (keyed by MAILBOX_SECRET), so the extractor can decrypt it too.
 */
export const aiSettings = pgTable("ai_settings", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  provider: aiProvider("provider").notNull().default("none"),
  /** encrypted API key; "" for ollama/none */
  apiKeyEnc: text("api_key_enc").notNull().default(""),
  /** base URL for ollama/custom; "" otherwise */
  baseUrl: text("base_url").notNull().default(""),
  /** model name; provider default used when "" */
  model: text("model").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Long-lived financial containers are accounts. Their current value is the
 * account balance; scheme-specific metadata lives in a one-to-one detail table.
 */
export const accountType = pgEnum("account_type", [
  "bank",
  "cash",
  "credit_card",
  "investment",
  "loan",
  // Generic overdraft/line-of-credit account. It shares drawing-power details
  // with an overdraft home loan but is kept distinct for reporting and labels.
  "overdraft",
  "ppf",
  "epf",
  // Sukanya Samriddhi: a PPF twin (fixed govt rate, credited annually, matures
  // ~21 years out, has an account number). Reuses the scheme-details structure.
  "ssy",
  "nps",
  // Overdraft home loan (SBI Maxgain and its equivalents). A distinct type, not
  // just a loan: you park surplus into it to cut interest and can withdraw it
  // back, so it carries a sanctioned limit and a drawing power a term loan has
  // no notion of. The balance is still what you owe (net of parked surplus), so
  // it lands in the loans bucket like any liability.
  "home_loan_od",
  // DEPRECATED: insurance is now a standalone entity (see insurance_policies),
  // not an account. This enum value is retained only because Postgres cannot drop
  // an enum value; no account uses it and the UI no longer offers it.
  "insurance",
]);

export const accounts = pgTable(
  "accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** human-facing label, e.g. "HDFC Joint" — never parsed; display comes from this alone */
    name: text("name").notNull(),
    type: accountType("type").notNull(),
    /** issuing bank/institution; a lookup key for import matching, not a display badge */
    institution: text("institution"),
    /**
     * Last 4 digits, shown in lists so two HDFC accounts are tellable apart.
     * Derived from bank_details.account_number whenever one exists — see
     * syncAccountLast4 — so the two can never disagree. Set by hand only when
     * the full number isn't recorded.
     */
    accountLast4: text("account_last4"),
    /**
     * Whose account this is. Universal, not bank-only: a card has a name on it
     * and a PPF has a holder. Without this the holder gets packed into `name`
     * ("HDFC Ammu PPF"), which is the same trap the last-4 used to be in.
     */
    holderName: text("holder_name"),
    /**
     * UPI handles that resolve to this account, primary first. Not bank-only —
     * RuPay credit cards link to UPI too, so this can't live on bank_details.
     */
    upiIds: text("upi_ids")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    currency: text("currency").notNull().default("INR"),
    openingBalancePaise: bigint("opening_balance_paise", { mode: "number" })
      .notNull()
      .default(0),
    /**
     * Goal this account is earmarked for; net worth and goal funding group by
     * it. Null = the "Unassigned" bucket. Set-null on goal delete so the account
     * survives. A goal's funded value is the sum of the assets that point here.
     */
    // AnyPgColumn keeps inference stable across the accounts → goals reference
    // (goals is declared after accounts in this file).
    goalId: uuid("goal_id").references((): AnyPgColumn => goals.id, { onDelete: "set null" }),
    sortOrder: integer("sort_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("accounts_user_idx").on(t.userId)],
);

export const categoryKind = pgEnum("category_kind", ["income", "expense"]);

/** See ExpenseNecessitySchema in packages/shared — null = not yet decided. */
export const expenseNecessity = pgEnum("expense_necessity", ["essential", "non_essential"]);

export const categories = pgTable(
  "categories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    kind: categoryKind("kind").notNull(),
    /**
     * DEFAULT need-vs-want for transactions in this category. A transaction's own
     * `necessity` column overrides it — see `effectiveNecessity` in
     * packages/shared. Nullable on purpose: null is "undecided", a state reports
     * must show rather than guess.
     *
     * Always null for income categories: services/categories.ts enforces that on
     * both read and write, and the `categories_necessity_expense_only` check
     * constraint below makes a violating row unstorable even on the
     * backup-restore path, which bypasses those services entirely.
     */
    necessity: expenseNecessity("necessity"),
    parentId: uuid("parent_id"),
    icon: text("icon").notNull().default(""),
    color: text("color").notNull().default(""),
    sortOrder: integer("sort_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("categories_user_idx").on(t.userId),
    uniqueIndex("categories_user_name_parent_idx").on(t.userId, t.name, t.parentId),
    // Storage-level guarantee, not just a service-level one: backup restore
    // copies archive columns straight into this table (services/restore-user.ts,
    // db/restore.ts), bypassing the guards in services/categories.ts. Masking a
    // bad value on read is not the same as making it unstorable.
    check("categories_necessity_expense_only", sql`${t.necessity} is null or ${t.kind} = 'expense'`),
  ],
);

export const transactionSource = pgEnum("transaction_source", ["manual", "import", "recurring"]);

export const resourceKind = pgEnum("resource_kind", [
  "vehicle",
  "electricity",
  "mobile",
  "internet",
  "gas",
  "water",
  "other",
]);

/** A physical asset or service connection that expenses can be attributed to. */
export const resources = pgTable(
  "resources",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id").notNull().references(() => users.id),
    kind: resourceKind("kind").notNull(),
    name: text("name").notNull(),
    /** registration, consumer/account number, or mobile number */
    identifier: text("identifier").notNull().default(""),
    provider: text("provider").notNull().default(""),
    planName: text("plan_name").notNull().default(""),
    details: text("details").notNull().default(""),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("resources_user_kind_idx").on(t.userId, t.kind, t.name)],
);

export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    date: date("date").notNull(),
    /**
     * Precise transaction instant when known (a card alert / statement line
     * prints a time); null for date-only sources (CSV, manual). `date` stays the
     * authoritative day for ordering/reports — this only sharpens statement↔ledger
     * matching, where amount + timestamp uniquely ties a line to its ledger row.
     */
    occurredAt: timestamp("occurred_at", { withTimezone: true }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    merchant: text("merchant").notNull().default(""),
    categoryId: uuid("category_id").references(() => categories.id),
    /**
     * Need-vs-want for this specific spend, overriding the category's default.
     * Null = inherit (see `effectiveNecessity` in packages/shared).
     *
     * No check constraint like `categories` has: a transaction carries no `kind`
     * to contradict, and sign alone does not disqualify a row — a refund against
     * an essential purchase is still essential spend being reversed.
     */
    necessity: expenseNecessity("necessity"),
    notes: text("notes").notNull().default(""),
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    source: transactionSource("source").notNull().default("manual"),
    /**
     * True for the single seed row carrying a bank/cash account's starting
     * balance, so the account ledger reconciles instead of a balance appearing
     * from a hidden column. Excluded from income/expense/spend aggregations the
     * same way transfers are. A boolean (not a new `source` enum value) so the
     * marker is usable in the same migration transaction that adds it.
     */
    isOpening: boolean("is_opening").notNull().default(false),
    /**
     * Insurance policy this expense pays a premium for — a link to an
     * insurance_policies row, kept apart from `accountId` (the account the money
     * left). Null for ordinary transactions. Lets a policy show its premium
     * history without being an account itself. See services/insurance.ts.
     */
    policyId: uuid("policy_id").references((): AnyPgColumn => insurancePolicies.id, {
      onDelete: "set null",
    }),
    resourceId: uuid("resource_id").references(() => resources.id, { onDelete: "set null" }),
    recurringTemplateId: uuid("recurring_template_id").references(
      (): AnyPgColumn => recurringTemplates.id,
      { onDelete: "set null" },
    ),
    /**
     * The statement cycle that cleared this transaction — set when a statement
     * line matched it (see statement_reconciliations). A set-once-per-cycle stamp:
     * the reconciler clears and re-applies it on replay, so it always reflects the
     * latest processing of that cycle. Null for anything a statement hasn't cleared.
     */
    reconciledStatementId: uuid("reconciled_statement_id").references(
      (): AnyPgColumn => statementReconciliations.id,
      { onDelete: "set null" },
    ),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("transactions_user_date_idx").on(
      t.userId,
      t.date.desc(),
      t.createdAt.desc(),
      t.id.desc(),
    ),
    index("transactions_account_idx").on(t.accountId),
    index("transactions_category_idx").on(t.categoryId),
    index("transactions_policy_idx").on(t.policyId),
    index("transactions_resource_idx").on(t.resourceId),
    index("transactions_recurring_template_idx").on(t.recurringTemplateId),
    index("transactions_reconciled_idx").on(t.reconciledStatementId),
  ],
);

export const transactionSplits = pgTable(
  "transaction_splits",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    note: text("note").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("transaction_splits_tx_idx").on(t.transactionId)],
);

export const transferLinks = pgTable(
  "transfer_links",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    outTransactionId: uuid("out_transaction_id")
      .notNull()
      .unique()
      .references(() => transactions.id, { onDelete: "cascade" }),
    inTransactionId: uuid("in_transaction_id")
      .notNull()
      .unique()
      .references(() => transactions.id, { onDelete: "cascade" }),
    auto: boolean("auto").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("transfer_links_user_idx").on(t.userId)],
);

// ---------- Phase 2: imports & rules ----------

export const importStatus = pgEnum("import_status", ["staged", "committed", "rolled_back"]);

export const imports = pgTable(
  "imports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    fileName: text("file_name").notNull(),
    status: importStatus("status").notNull().default("staged"),
    mapping: jsonb("mapping"),
    headers: text("headers").array().notNull().default(sql`'{}'::text[]`),
    rowCount: integer("row_count").notNull().default(0),
    errorCount: integer("error_count").notNull().default(0),
    committedAt: timestamp("committed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("imports_user_idx").on(t.userId)],
);

export const importRows = pgTable(
  "import_rows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    importId: uuid("import_id")
      .notNull()
      .references(() => imports.id, { onDelete: "cascade" }),
    rowIndex: integer("row_index").notNull(),
    raw: jsonb("raw").notNull(),
    date: date("date"),
    amountPaise: bigint("amount_paise", { mode: "number" }),
    merchant: text("merchant").notNull().default(""),
    rawMerchant: text("raw_merchant").notNull().default(""),
    notes: text("notes").notNull().default(""),
    categoryId: uuid("category_id"),
    dedupeHash: text("dedupe_hash"),
    duplicate: boolean("duplicate").notNull().default(false),
    include: boolean("include").notNull().default(true),
    error: text("error"),
    transactionId: uuid("transaction_id"),
    /**
     * When this row reconciled by *correcting* an existing imported transaction,
     * the pre-update snapshot of that transaction ({ transactionId, date,
     * amountPaise, merchant, notes, source }) — so rollback can restore it.
     */
    reconciledFrom: jsonb("reconciled_from"),
  },
  (t) => [
    index("import_rows_import_idx").on(t.importId),
    index("import_rows_hash_idx").on(t.dedupeHash),
  ],
);

export const importPresets = pgTable(
  "import_presets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    name: text("name").notNull(),
    mapping: jsonb("mapping").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("import_presets_account_idx").on(t.userId, t.accountId)],
);

export const merchantRules = pgTable(
  "merchant_rules",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    match: text("match").notNull(),
    replacement: text("replacement").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("merchant_rules_user_match_idx").on(t.userId, t.match)],
);

// ---------- Phase 3: budgets, notifications, recurring ----------

export const budgetPeriod = pgEnum("budget_period", ["monthly", "annual"]);

export const budgets = pgTable(
  "budgets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    period: budgetPeriod("period").notNull().default("monthly"),
    /** "2026-07" for monthly, "2026" for annual */
    periodKey: text("period_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("budgets_user_period_idx").on(t.userId, t.period, t.periodKey)],
);

export const budgetLines = pgTable(
  "budget_lines",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    budgetId: uuid("budget_id")
      .notNull()
      .references(() => budgets.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "cascade" }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    rollover: boolean("rollover").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("budget_lines_budget_category_idx").on(t.budgetId, t.categoryId)],
);

/** Dedup ledger: one alert per (period, category, threshold) — never re-fires. */
export const budgetAlerts = pgTable(
  "budget_alerts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    periodKey: text("period_key").notNull(),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "cascade" }),
    threshold: integer("threshold").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("budget_alerts_unique_idx").on(t.userId, t.periodKey, t.categoryId, t.threshold),
  ],
);

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    type: text("type").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull().default(""),
    data: jsonb("data"),
    readAt: timestamp("read_at", { withTimezone: true }),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("notifications_user_idx").on(t.userId, t.createdAt.desc())],
);

export const recurringFrequency = pgEnum("recurring_frequency", [
  "daily",
  "weekly",
  "monthly",
  "yearly",
]);

export const recurringKind = pgEnum("recurring_kind", [
  "none",
  "bill",
  "subscription",
  "insurance",
  "emi",
]);

export const recurringTemplates = pgTable(
  "recurring_templates",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id),
    categoryId: uuid("category_id").references(() => categories.id),
    merchant: text("merchant").notNull(),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    notes: text("notes").notNull().default(""),
    frequency: recurringFrequency("frequency").notNull(),
    interval: integer("interval").notNull().default(1),
    nextDueDate: date("next_due_date").notNull(),
    endDate: date("end_date"),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    /** bill/subscription/insurance/EMI typing for the Bills view; none = plain recurring */
    kind: recurringKind("kind").notNull().default("none"),
    /** reminder lead days; null = per-kind default (3, annual 14) */
    remindDays: integer("remind_days"),
    resourceId: uuid("resource_id").references(() => resources.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("recurring_templates_user_idx").on(t.userId, t.nextDueDate)],
);

// ---------- Phase 4: goals, bills, notification prefs ----------

export const goalType = pgEnum("goal_type", [
  "savings",
  "emergency_fund",
  "vacation",
  "home",
  "vehicle",
  "education",
  "retirement",
  "custom",
]);

export const goals = pgTable(
  "goals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    type: goalType("type").notNull().default("savings"),
    targetPaise: bigint("target_paise", { mode: "number" }),
    /** emergency_fund preset: target = N months of trailing average expenses */
    targetMonths: integer("target_months"),
    targetDate: date("target_date"),
    sortOrder: integer("sort_order").notNull().default(0),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("goals_user_idx").on(t.userId)],
);

/** Generic once-only ledger for milestone/reminder/threshold notifications. */
export const alertLedger = pgTable(
  "alert_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    kind: text("kind").notNull(),
    refKey: text("ref_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("alert_ledger_unique_idx").on(t.userId, t.kind, t.refKey)],
);

export const subscriptionDismissals = pgTable(
  "subscription_dismissals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    merchant: text("merchant").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("subscription_dismissals_unique_idx").on(t.userId, t.merchant)],
);

export const notificationPrefs = pgTable(
  "notification_prefs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** budget | bill | goal | large_transaction | low_balance */
    type: text("type").notNull(),
    /** null = applies to all accounts */
    accountId: uuid("account_id").references(() => accounts.id, { onDelete: "cascade" }),
    enabled: boolean("enabled").notNull().default(true),
    thresholdPaise: bigint("threshold_paise", { mode: "number" }),
    leadDays: integer("lead_days"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("notification_prefs_user_idx").on(t.userId, t.type)],
);

export const attachments = pgTable(
  "attachments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    storedPath: text("stored_path").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("attachments_tx_idx").on(t.transactionId)],
);

// ---------- Phase 5: cards, EMIs, holdings, net worth ----------

export const cardNetwork = pgEnum("card_network", [
  "visa",
  "mastercard",
  "amex",
  "rupay",
  "diners",
]);

/**
 * Issuer and last-4 live on `accounts` (institution/accountLast4) — every
 * account has them. Card-specific fields belong here; the genuinely shared
 * fields (combined limit, mobile, utilization/reminder alerts) live on
 * `card_issuer_settings`, keyed by the account's institution. The statement-PDF
 * password stays per-card: issuers like HDFC embed the card's own last-4 in it,
 * so one bank's cards each need their own.
 */
export const cardDetails = pgTable("card_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  network: cardNetwork("network"),
  /** product name, e.g. "Regalia Gold" */
  productName: text("product_name").notNull().default(""),
  /** statement close day of month (1–28) */
  cycleDay: integer("cycle_day").notNull().default(1),
  /** payment due day of month (1–28); first occurrence after the close */
  dueDay: integer("due_day").notNull().default(15),
  /** reward points earned per ₹100 spent (0 = no program) */
  earnRatePer100: integer("earn_rate_per_100").notNull().default(0),
  /**
   * Password to open this card's statement PDFs, encrypted at rest (secret-box).
   * "" when unset. Never returned to the client — the API exposes only whether
   * one is stored (see CardDetails.hasStatementPassword).
   */
  statementPasswordEnc: text("statement_password_enc").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Settings shared across every card of one bank/issuer. In India an issuer
 * typically gives a single combined credit limit spanning all your cards with
 * them, and the registered mobile is the same across those cards — so these
 * live at the issuer level, keyed by (user, institution), not per card. (The
 * statement password is NOT shared — it's per-card, on `card_details`.) The
 * `institution` matches `accounts.institution`; cards with no institution set
 * have no issuer settings (each is its own "unassigned" holder).
 */
export const cardIssuerSettings = pgTable(
  "card_issuer_settings",
  {
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** the group key; matches accounts.institution exactly */
    institution: text("institution").notNull(),
    /** combined credit limit shared across all this bank's cards */
    creditLimitPaise: bigint("credit_limit_paise", { mode: "number" }).notNull().default(0),
    /** alert when combined utilization crosses this percentage; null disables */
    utilizationAlertPct: integer("utilization_alert_pct").default(30),
    /** days before a card's due date to send the payment reminder */
    remindDays: integer("remind_days").notNull().default(3),
    /**
     * Registered mobile (10 digits, no country code) for building the bill-payment
     * UPI VPA — e.g. Axis `CC.91<mobile><last4>@axisbank`. Empty when unknown or
     * the issuer has no VPA scheme.
     */
    billMobile: text("bill_mobile").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.institution] })],
);

/**
 * Statement PDFs (or images) a user uploads for a credit card, stored in object
 * storage (MinIO) with only the metadata row here. Kept per card — the file is
 * shown on that card's detail page. `period` tags the statement's close/month so
 * they sort meaningfully; null when the user didn't say. Mirrors the attachment /
 * health-card storage pattern (opaque storedPath key, cascade on account delete).
 */
export const cardStatements = pgTable(
  "card_statements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** the statement's close/period date; null when unspecified */
    period: date("period"),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    storedPath: text("stored_path").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("card_statements_account_idx").on(t.accountId, t.period)],
);

/**
 * Extra detail for `ppf`/`epf` accounts. Mirrors the card_details pattern: a
 * 1:1 optional extension keyed by account, so the core accounts table stays
 * free of type-specific columns.
 */
export const bankAccountSubtype = pgEnum("bank_account_subtype", [
  "savings",
  "current",
  "salary",
  "nre",
  "nro",
]);

/**
 * The details you'd read out to someone paying you. Holder name and UPI live on
 * `accounts` (every type has them); only bank-specific fields belong here.
 *
 * The account number is stored in the clear on purpose: it is a receiving
 * address, not a secret — it's printed on cheques and handed to employers, and
 * money cannot be pulled with it. Encrypting it would cost searchability and a
 * key to lose, while protecting a value that gets given out by design.
 */
export const bankDetails = pgTable("bank_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** full account number; digits only, length varies by bank (9–18) */
  accountNumber: text("account_number").notNull().default(""),
  /** IFSC, e.g. "HDFC0001234" — 4 letters, a literal 0, then 6 alphanumeric */
  ifsc: text("ifsc").notNull().default(""),
  branch: text("branch").notNull().default(""),
  subtype: bankAccountSubtype("subtype"),
  /** Required Average Monthly Balance for this account, in integer paise. 0 = no requirement set. */
  requiredAmbPaise: bigint("required_amb_paise", { mode: "number" }).notNull().default(0),
  /** last 4 of the debit card linked to this account; matches debit-card alert emails */
  debitCardLast4: text("debit_card_last4").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const retirementDetails = pgTable("retirement_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** annual interest rate in basis points (710 = 7.10%) */
  annualRateBps: integer("annual_rate_bps").notNull().default(0),
  /** PPF matures 15 years from opening; EPF has no maturity, so null */
  maturityDate: date("maturity_date"),
  /** UAN for EPF, account number for PPF — free-form, may be non-numeric */
  referenceNumber: text("reference_number").notNull().default(""),
  /**
   * EPF only: the accumulated Employee Pension Scheme (EPS) balance. EPFO tracks
   * it separately from the provident-fund corpus, so it's a distinct figure the
   * account balance doesn't include. Null for PPF/SSY (and for EPF until entered).
   */
  epsBalancePaise: bigint("eps_balance_paise", { mode: "number" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Extra detail for generic overdraft and `home_loan_od` accounts.
 *
 * Only the sanctioned limit is stored — the amount owed is the account balance
 * (already net of parked surplus, like the bank's own screen), and drawing
 * power derives as limit − owed. Storing surplus separately would let it drift
 * from the balance; deriving it keeps one source of truth.
 */
export const overdraftDetails = pgTable("overdraft_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  /** drawing-power ceiling, i.e. the bank's "Limit" figure */
  sanctionedLimitPaise: bigint("sanctioned_limit_paise", { mode: "number" }).notNull().default(0),
  /** annual interest rate in basis points (855 = 8.55%); drives the interest-saved estimate */
  annualRateBps: integer("annual_rate_bps").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insuranceKind = pgEnum("insurance_kind", ["life", "health", "vehicle"]);
export const vehicleKind = pgEnum("vehicle_kind", ["car", "bike", "other"]);
export const healthType = pgEnum("health_type", [
  "indemnity",
  "top_up",
  "critical_illness",
  "hospital_cash",
  "personal_accident",
  "disease_specific",
]);
export const premiumFrequency = pgEnum("premium_frequency", [
  "monthly",
  "quarterly",
  "half_yearly",
  "yearly",
  "single",
]);

/**
 * An insurance policy — a standalone record, not an account. It carries its own
 * fields (insurer, policy number, sum assured, bonus, dates) rather than the
 * name/holder/UPI/balance an account has, because a policy isn't money you hold.
 * Premiums are tracked as ordinary expense transactions tagged with policy_id
 * (see transactions.policyId); the money flow lives there, only the standing
 * policy terms live here.
 */
export const insurancePolicies = pgTable(
  "insurance_policies",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** short display label for lists, e.g. "LIC Jeevan Anand" */
    name: text("name").notNull(),
    kind: insuranceKind("kind").notNull().default("life"),
    /** car/bike/other for a vehicle policy; null for life/health */
    vehicleType: vehicleKind("vehicle_type"),
    /** vehicle registration number; "" for non-vehicle policies */
    vehicleRegNo: text("vehicle_reg_no").notNull().default(""),
    /** canonical vehicle record; legacy type/registration fields remain for compatibility */
    resourceId: uuid("resource_id").references(() => resources.id, { onDelete: "set null" }),
    /** indemnity/critical-illness/etc. for a health policy; null for life/vehicle */
    healthType: healthType("health_type"),
    /** insurance company, e.g. "LIC", "Star Health" */
    insurer: text("insurer").notNull().default(""),
    policyNumber: text("policy_number").notNull().default(""),
    /** URL to the policy wordings/terms doc; "" when unset. For agents to read later. */
    policyWordingUrl: text("policy_wording_url").notNull().default(""),
    /** sum assured (life) / sum insured (health) / IDV (vehicle), in paise */
    sumAssuredPaise: bigint("sum_assured_paise", { mode: "number" }).notNull().default(0),
    /** accrued bonus / loyalty additions (endowment life), in paise */
    bonusPaise: bigint("bonus_paise", { mode: "number" }).notNull().default(0),
    /** premium per payment, in paise */
    premiumPaise: bigint("premium_paise", { mode: "number" }).notNull().default(0),
    premiumFrequency: premiumFrequency("premium_frequency").notNull().default("yearly"),
    /** policy commencement ("started from") */
    startDate: date("start_date"),
    /** next renewal / premium due date */
    renewalDate: date("renewal_date"),
    /** endowment/money-back maturity; null for pure term, health, vehicle */
    maturityDate: date("maturity_date"),
    nominee: text("nominee").notNull().default(""),
    /** people covered by the policy — e.g. a family-floater's members. */
    coveredMembers: text("covered_members")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    /** uploaded policy document (single file, stored like an attachment); null when none. */
    documentPath: text("document_path"),
    documentName: text("document_name"),
    documentMime: text("document_mime"),
    documentSizeBytes: integer("document_size_bytes"),
    notes: text("notes").notNull().default(""),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("insurance_policies_user_idx").on(t.userId)],
);

/**
 * Health cards for a policy — a family-floater has one per covered member, so a
 * policy can have several. Files go through the storage layer like attachments;
 * each card optionally names the member it belongs to.
 */
export const insuranceHealthCards = pgTable(
  "insurance_health_cards",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    policyId: uuid("policy_id")
      .notNull()
      .references(() => insurancePolicies.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    /** which member this card is for, e.g. "Spouse"; "" when unlabeled */
    label: text("label").notNull().default(""),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    storedPath: text("stored_path").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("insurance_health_cards_policy_idx").on(t.policyId)],
);

export const rewardEntries = pgTable(
  "reward_entries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    /** positive = earned, negative = redeemed/expired */
    points: integer("points").notNull(),
    note: text("note").notNull().default(""),
    /**
     * The statement ingestion that produced this entry (null = hand-entered). Lets
     * a statement's reward rows be replaced wholesale on replay so re-processing
     * never double-counts the balance. Kept (unlinked) if the ingestion is deleted.
     */
    ingestionId: uuid("ingestion_id").references(() => emailIngestions.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("reward_entries_account_idx").on(t.accountId, t.date),
    index("reward_entries_ingestion_idx").on(t.ingestionId),
  ],
);

/**
 * One row per card per statement cycle — the reconciliation snapshot. Written by
 * the extractor when it processes a statement: it matches the statement's lines to
 * ledger transactions already recorded from real-time alerts, stamps those ledger
 * rows (`transactions.reconciled_statement_id`), and records the cycle's totals +
 * match stats here. Keyed on `(account_id, period)` — NOT the ingestion — so a
 * mailbox's duplicate statement emails collapse to one record and a replay updates
 * in place instead of piling up. `period` is the statement/received month "YYYY-MM".
 */
export const statementReconciliations = pgTable(
  "statement_reconciliations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    /** the statement cycle, "YYYY-MM"; the idempotency key with account_id */
    period: text("period").notNull(),
    /** the statement's close date, when it stated one */
    statementDate: date("statement_date"),
    /** the last statement email that produced this row — informational, not the key */
    ingestionId: uuid("ingestion_id").references(() => emailIngestions.id, {
      onDelete: "set null",
    }),
    // Summary snapshot (from the statement's totals block; null when not stated).
    totalDuePaise: bigint("total_due_paise", { mode: "number" }),
    minDuePaise: bigint("min_due_paise", { mode: "number" }),
    rewardOpening: integer("reward_opening"),
    rewardEarned: integer("reward_earned"),
    rewardRedeemed: integer("reward_redeemed"),
    rewardClosing: integer("reward_closing"),
    // Match stats over the statement's own transaction lines.
    /** statement transaction lines extracted */
    lineCount: integer("line_count").notNull().default(0),
    /** sum of the debit (spend) lines' magnitudes, in paise */
    lineDebitPaise: bigint("line_debit_paise", { mode: "number" }).notNull().default(0),
    /** lines matched to a ledger transaction already recorded this cycle */
    matchedCount: integer("matched_count").notNull().default(0),
    /** sum of the matched lines' magnitudes, in paise */
    matchedPaise: bigint("matched_paise", { mode: "number" }).notNull().default(0),
    /** lines with no ledger match — new drafts / exceptions to review */
    unmatchedCount: integer("unmatched_count").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("statement_reconciliations_cycle_idx").on(t.accountId, t.period),
    index("statement_reconciliations_user_idx").on(t.userId, t.accountId),
  ],
);

export const emiDetails = pgTable("emi_details", {
  templateId: uuid("template_id")
    .primaryKey()
    .references(() => recurringTemplates.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  principalPaise: bigint("principal_paise", { mode: "number" }).notNull(),
  /** annual interest rate in basis points (875 = 8.75%) */
  annualRateBps: integer("annual_rate_bps").notNull(),
  totalInstallments: integer("total_installments").notNull(),
  /** first installment date */
  startDate: date("start_date").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * No ppf/epf here — those are account types. Their balance is a credited fact,
 * not a valuation, so modelling them as holdings would dress a known number up
 * as an estimate (and give the user two places to record the same thing).
 */
export const assetClass = pgEnum("asset_class", [
  "stock",
  "mutual_fund",
  "etf",
  "gold",
  "silver",
  "fd",
  "nps",
  "real_estate",
  "other",
]);

/**
 * How a holding's capital gains are taxed. A per-holding fact that can't be
 * inferred from asset_class (a mutual_fund may be equity, debt, or a §50AA
 * specified fund), so it's stored and user-settable. See services/tax-lots.ts.
 */
export const gainsTaxClass = pgEnum("gains_tax_class", [
  "equity",
  "unlisted_shares",
  "other",
  "specified_fund",
  "market_linked_debenture",
  "unlisted_bond",
  "exempt",
]);

export const holdings = pgTable(
  "holdings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    name: text("name").notNull(),
    assetClass: assetClass("asset_class").notNull(),
    notes: text("notes").notNull().default(""),
    /** optional allocation target, % of portfolio */
    targetPct: integer("target_pct"),
    /**
     * AMFI scheme code (6 digits, e.g. 122639). The key NAV refresh looks up.
     * Null = unmapped: a fund with no AMFI scheme (e.g. a platform product like
     * Kuvera SaveSmart), valued from imported data only and skipped by refresh.
     */
    amfiSchemeCode: integer("amfi_scheme_code"),
    /** MF folio number; free-form, may be non-numeric */
    folioNumber: text("folio_number"),
    /**
     * NAV per unit on 31-Jan-2018 in paise, for grandfathering equity units held
     * before 01-Feb-2018 in the capital-gains statement. Null = not set (no old
     * units, or the user hasn't supplied the FMV). See services/tax-lots.ts.
     */
    grandfatherNavPaise: bigint("grandfather_nav_paise", { mode: "number" }),
    /** Capital-gains tax treatment; guessed from asset class at create, user-editable. */
    gainsTaxClass: gainsTaxClass("gains_tax_class").notNull().default("equity"),
    /** Goal this holding (folio) is earmarked for; null = "Unassigned". See accounts.goalId. */
    goalId: uuid("goal_id").references(() => goals.id, { onDelete: "set null" }),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("holdings_user_idx").on(t.userId)],
);

export const npsTier = pgEnum("nps_tier", ["tier_i", "tier_ii"]);

/** Scheme metadata for an NPS account; its corpus is the account balance. */
export const accountNpsDetails = pgTable("account_nps_details", {
  accountId: uuid("account_id")
    .primaryKey()
    .references(() => accounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  pran: text("pran").notNull().default(""),
  tier: npsTier("tier").notNull().default("tier_i"),
  /** Current E/C/G scheme allocation; validated to total 100 by the service. */
  equityPct: integer("equity_pct").notNull().default(0),
  corporatePct: integer("corporate_pct").notNull().default(0),
  govtPct: integer("govt_pct").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Extra detail for legacy `nps` holdings. */
export const npsDetails = pgTable("nps_details", {
  holdingId: uuid("holding_id")
    .primaryKey()
    .references(() => holdings.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  pran: text("pran").notNull().default(""),
  tier: npsTier("tier").notNull().default("tier_i"),
  /** scheme allocation, percent; E + C + G must total 100 (enforced in the service) */
  equityPct: integer("equity_pct").notNull().default(0),
  corporatePct: integer("corporate_pct").notNull().default(0),
  govtPct: integer("govt_pct").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const goldForm = pgEnum("gold_form", ["physical", "digital", "etf", "sgb"]);

/** Extra detail for `gold` holdings. */
export const goldDetails = pgTable("gold_details", {
  holdingId: uuid("holding_id")
    .primaryKey()
    .references(() => holdings.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  form: goldForm("form").notNull().default("physical"),
  /** karat, physical/digital only (22 or 24); null for etf/sgb */
  purityKarat: integer("purity_karat"),
  /** SGB matures 8 years from issue; null for every other form */
  maturityDate: date("maturity_date"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const holdingValuations = pgTable(
  "holding_valuations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    holdingId: uuid("holding_id")
      .notNull()
      .references(() => holdings.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    valuePaise: bigint("value_paise", { mode: "number" }).notNull(),
    /**
     * NAV per unit on `date` (from the AMFI feed), when known. Lets the day's
     * change be the true market move — (navToday − navPrev) on the held units —
     * rather than a raw value delta that a same-day buy would distort. Null for
     * manual valuations that only recorded a total value.
     */
    nav: doublePrecision("nav"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("holding_valuations_unique_idx").on(t.holdingId, t.date)],
);

export const holdingEventType = pgEnum("holding_event_type", ["buy", "sell", "dividend"]);

/** Where an event came from: a statement import, or hand-entered. Drives per-date
 * FIFO-order reconciliation on re-import (imports may re-sequence imported events;
 * manual ones are only ever moved by the user). See services/mf-import.ts. */
export const holdingEventSource = pgEnum("holding_event_source", ["import", "manual"]);

export const holdingEvents = pgTable(
  "holding_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    holdingId: uuid("holding_id")
      .notNull()
      .references(() => holdings.id, { onDelete: "cascade" }),
    type: holdingEventType("type").notNull(),
    date: date("date").notNull(),
    /** always positive; the type carries direction */
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    units: doublePrecision("units"),
    note: text("note").notNull().default(""),
    /**
     * Intra-day order key: the 0-based position of this event *within its
     * (holding, date)*. Both imported and manual events carry one, so a same-day
     * manual sale can sit before an imported buy. `date` is FIFO's primary key,
     * so seq only has to separate events sharing a day (see services/tax-lots.ts).
     * User-editable via the reorder endpoint.
     */
    seq: integer("seq"),
    /** import vs manual; default import (the dominant source). Manual adds set it. */
    source: holdingEventSource("source").notNull().default("import"),
    /**
     * The SIP installment this buy booked, when it was recorded from a SIP
     * rather than hand-entered or imported. `set null` on delete, not cascade:
     * deleting the SIP *plan* must not erase units the user really bought.
     */
    sipId: uuid("sip_id").references(() => sips.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("holding_events_holding_idx").on(t.holdingId, t.date),
    uniqueIndex("holding_events_sip_date_idx").on(t.sipId, t.date).where(sql`sip_id is not null`),
  ],
);

export const sipTargetKind = pgEnum("sip_target_kind", ["mf_folio", "account"]);
export const sipStatus = pgEnum("sip_status", ["active", "paused"]);
/**
 * How often the SIP debits. Most MF SIPs are monthly, but PPF/SSY are often
 * funded with a single lump quarterly/annual deposit rather than a monthly
 * trickle — this lets those goals still be modelled as a SIP instead of being
 * left out of the commitment math entirely.
 */
export const sipFrequency = pgEnum("sip_frequency", ["monthly", "quarterly", "yearly"]);

/**
 * A goal-funding SIP: a recurring monthly transfer from a bank/savings account
 * into either an MF folio (a `holdings` row — that table is already keyed by
 * scheme+folio, so the target is a direct FK, not duplicated scheme columns) or
 * another account (PPF/SSY deposits — think a Sukanya Samriddhi girl-child
 * goal). A goal can have several SIPs. Exactly one of `targetHoldingId` /
 * `targetAccountId` is set, matching `targetKind`; enforced in the service/zod
 * layer, not the DB, the same way accounts.goal_id's "one goal" isn't a DB
 * constraint either. Cascades on both the goal and the target: a SIP has no
 * purpose once either disappears (contrast accounts.goal_id, which set-nulls,
 * because an *account* survives its goal being deleted).
 */
export const sips = pgTable(
  "sips",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    goalId: uuid("goal_id")
      .notNull()
      .references(() => goals.id, { onDelete: "cascade" }),
    sourceAccountId: uuid("source_account_id")
      .notNull()
      .references(() => accounts.id),
    targetKind: sipTargetKind("target_kind").notNull(),
    /** set when targetKind = 'mf_folio'; the holdings row IS the scheme+folio position */
    targetHoldingId: uuid("target_holding_id").references(() => holdings.id, {
      onDelete: "cascade",
    }),
    /** set when targetKind = 'account' (e.g. PPF/SSY) */
    targetAccountId: uuid("target_account_id").references(() => accounts.id, {
      onDelete: "cascade",
    }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    /** debit day of month, 1–28 (validated at the zod layer, like card cycle/due day) */
    dayOfMonth: integer("day_of_month").notNull(),
    /**
     * Cadence of the debit. quarterly/yearly occurrences are anchored to the
     * month of `startDate` (see sipOccurrencesInWindow) — every 3rd/12th month
     * from there, on dayOfMonth.
     */
    frequency: sipFrequency("frequency").notNull().default("monthly"),
    status: sipStatus("status").notNull().default("active"),
    startDate: date("start_date").notNull(),
    endDate: date("end_date"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("sips_user_idx").on(t.userId),
    index("sips_goal_idx").on(t.goalId),
    index("sips_source_account_idx").on(t.sourceAccountId),
  ],
);

export const netWorthSnapshots = pgTable(
  "net_worth_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    date: date("date").notNull(),
    assetsPaise: bigint("assets_paise", { mode: "number" }).notNull(),
    liabilitiesPaise: bigint("liabilities_paise", { mode: "number" }).notNull(),
    /** { cash, holdings, investmentAccounts, creditCards, loans } */
    breakdown: jsonb("breakdown"),
    /** true when estimated from ledger history rather than observed */
    estimated: boolean("estimated").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("net_worth_snapshots_unique_idx").on(t.userId, t.date)],
);

// ---------- Phase 7: email → transaction ingestion pipeline ----------
//
// Two containers feed this: the `ingestor` (IMAP → raw email row + queue job)
// and the `extractor` (queue → AI classify/extract → review inbox). See
// packages/shared/src/schemas/email.ts for the wire contract shared between them.

export const mailboxProvider = pgEnum("mailbox_provider", ["google", "microsoft"]);
export const mailboxStatus = pgEnum("mailbox_status", ["active", "disconnected", "error"]);

/**
 * A connected mailbox. Holds the OAuth2 refresh token (encrypted at rest — no
 * password is ever stored) and the IMAP resume watermark so restarts never
 * reprocess mail. One row per mailbox the ingestor polls.
 */
export const mailboxAccounts = pgTable(
  "mailbox_accounts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    provider: mailboxProvider("provider").notNull(),
    emailAddress: text("email_address").notNull(),
    /** OAuth2 refresh token, encrypted with the app secret; minted into access tokens for XOAUTH2 */
    refreshTokenEnc: text("refresh_token_enc").notNull(),
    folder: text("folder").notNull().default("INBOX"),
    status: mailboxStatus("status").notNull().default("active"),
    lastError: text("last_error"),
    /** IMAP resume watermark: reprocess nothing at or below lastUid for this uidValidity */
    uidValidity: bigint("uid_validity", { mode: "number" }),
    lastUid: bigint("last_uid", { mode: "number" }),
    lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("mailbox_accounts_addr_idx").on(t.userId, t.emailAddress)],
);

/**
 * Per-user OAuth client credentials for a mailbox provider. Each user brings
 * their own Google Cloud OAuth client (there is no shared/global client), so
 * the client id + encrypted secret are stored here and resolved per mailbox by
 * the ingestor. One row per (user, provider).
 */
export const mailboxCredentials = pgTable(
  "mailbox_credentials",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    provider: mailboxProvider("provider").notNull(),
    clientId: text("client_id").notNull(),
    /** OAuth client secret, encrypted with the app secret (same envelope as the refresh token) */
    clientSecretEnc: text("client_secret_enc").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("mailbox_credentials_user_provider_idx").on(t.userId, t.provider)],
);

export const emailClass = pgEnum("email_class", [
  "transaction_alert",
  "card_statement",
  "bill",
  "otp",
  "promo",
  "other",
]);

export const emailIngestStatus = pgEnum("email_ingest_status", [
  "pending",
  "processing",
  "extracted",
  "deferred",
  "ignored",
  "failed",
]);

/**
 * One ingested email. The raw RFC822 message is retained (`raw`) so extraction
 * is replayable after a parser/prompt fix. `messageId` dedupes re-fetches.
 */
export const emailIngestions = pgTable(
  "email_ingestions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    mailboxId: uuid("mailbox_id").references(() => mailboxAccounts.id, { onDelete: "set null" }),
    /** RFC822 Message-ID header; the dedupe key for re-fetched mail */
    messageId: text("message_id").notNull(),
    fromAddr: text("from_addr").notNull().default(""),
    subject: text("subject").notNull().default(""),
    receivedAt: timestamp("received_at", { withTimezone: true }),
    /** full RFC822 message (MIME is ascii-safe), retained for replay */
    raw: text("raw").notNull(),
    classification: emailClass("classification"),
    status: emailIngestStatus("status").notNull().default("pending"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("email_ingestions_msgid_idx").on(t.userId, t.messageId),
    index("email_ingestions_status_idx").on(t.userId, t.status),
  ],
);

export const extractedTxnStatus = pgEnum("extracted_txn_status", [
  "pending",
  "accepted",
  "rejected",
  // A statement line the matcher tied to a transaction already in the ledger —
  // hidden from the pending queue, kept (linked, reversible) so nothing is lost.
  "duplicate",
]);
export const txnDirection = pgEnum("txn_direction", ["debit", "credit"]);

/**
 * A transaction the model pulled out of an email — a draft in the review inbox.
 * `amountPaise` is a positive magnitude; `direction` gives the sign applied when
 * the reviewer accepts it into the ledger. Category is never set here (accept is
 * a manual step). `dedupeHash` collapses the alert and the later statement line.
 */
export const extractedTransactions = pgTable(
  "extracted_transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    ingestionId: uuid("ingestion_id")
      .notNull()
      .references(() => emailIngestions.id, { onDelete: "cascade" }),
    amountPaise: bigint("amount_paise", { mode: "number" }).notNull(),
    direction: txnDirection("direction").notNull(),
    occurredAt: date("occurred_at"),
    /**
     * Precise instant the line/alert prints (`occurredAt` keeps the date). Carried
     * to `transactions.occurred_at` on accept and used as the primary statement↔
     * ledger match key; null when the source shows only a date.
     */
    occurredAtTs: timestamp("occurred_at_ts", { withTimezone: true }),
    counterparty: text("counterparty").notNull().default(""),
    suggestedAccountId: uuid("suggested_account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    /** AI's category guess from the merchant; the reviewer confirms/overrides on accept */
    suggestedCategoryId: uuid("suggested_category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    bankRef: text("bank_ref"),
    sourceQuote: text("source_quote").notNull().default(""),
    confidence: doublePrecision("confidence"),
    /** bank_ref, or a hash of amount+date+counterparty; unique to collapse duplicates */
    dedupeHash: text("dedupe_hash"),
    status: extractedTxnStatus("status").notNull().default("pending"),
    /** set once accepted into the ledger */
    transactionId: uuid("transaction_id").references(() => transactions.id, {
      onDelete: "set null",
    }),
    /**
     * The ledger transaction this draft was matched to (status `duplicate`): the
     * statement re-listed a spend already recorded from a real-time alert. Set by
     * the statement matcher; cleared if the reviewer says it isn't a duplicate.
     */
    matchedTransactionId: uuid("matched_transaction_id").references(() => transactions.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("extracted_transactions_status_idx").on(t.userId, t.status),
    index("extracted_transactions_ingestion_idx").on(t.ingestionId),
    uniqueIndex("extracted_transactions_dedupe_idx").on(t.userId, t.dedupeHash),
  ],
);

// ---------- AI event log ----------

export const aiEventKind = pgEnum("ai_event_kind", [
  "email_extract", // an ingested email classified/extracted by the model
  "statement_parse", // a credit-card statement PDF's lines parsed
  "statement_summary", // a statement's rewards/summary parsed
  "categorize", // in-app "Suggest categories"
  "summary", // the monthly narrative summary
  "assistant", // an assistant chat turn
]);
export const aiEventStatus = pgEnum("ai_event_status", ["ok", "error"]);

/**
 * One model call, logged for transparency: what context was sent to the LLM and
 * what came back, plus provider/model/latency. Both the API and the extractor
 * write here. `requestContext`/`responseRaw` are the exact strings exchanged, so
 * the event log can show precisely what left the app (only subject/from/body of a
 * mail is ever sent — never the raw headers).
 */
export const aiEvents = pgTable(
  "ai_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    kind: aiEventKind("kind").notNull(),
    status: aiEventStatus("status").notNull(),
    provider: text("provider").notNull().default(""),
    model: text("model").notNull().default(""),
    /** short label for the list row (email subject, "12 transactions", …) */
    title: text("title").notNull().default(""),
    ingestionId: uuid("ingestion_id").references(() => emailIngestions.id, { onDelete: "set null" }),
    accountId: uuid("account_id").references(() => accounts.id, { onDelete: "set null" }),
    /** exactly what was sent to the model (system + user context), as text */
    requestContext: text("request_context").notNull().default(""),
    /** raw text the model returned */
    responseRaw: text("response_raw").notNull().default(""),
    latencyMs: integer("latency_ms"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("ai_events_user_created_idx").on(t.userId, t.createdAt.desc())],
);
